const $ = (s) => document.querySelector(s);
const USERS_KEY='shurangan_users', CURRENT_KEY='shurangan_current_user';
const demoUsers=[
 {name:'Rafi Hasan',email:'student@shurangan.bd',phone:'01700000001',password:'123456',role:'student'},
 {name:'Nusrat Rahman',email:'teacher@shurangan.bd',phone:'01700000002',password:'123456',role:'teacher'},
 {name:'System Administrator',email:'admin@shurangan.bd',phone:'01700000003',password:'123456',role:'admin'}
];
if(!localStorage.getItem(USERS_KEY)) localStorage.setItem(USERS_KEY,JSON.stringify(demoUsers));
function users(){return JSON.parse(localStorage.getItem(USERS_KEY)||'[]')}
function saveUsers(v){localStorage.setItem(USERS_KEY,JSON.stringify(v))}
function openAuth(mode='login'){ $('#authModal').classList.remove('hidden'); switchAuth(mode); document.body.style.overflow='hidden'; }
function closeAuth(){ $('#authModal').classList.add('hidden'); document.body.style.overflow=''; }
function switchAuth(mode){
 $('#loginForm').classList.toggle('hidden',mode!=='login'); $('#signupForm').classList.toggle('hidden',mode!=='signup');
 $('#loginTab').classList.toggle('active',mode==='login'); $('#signupTab').classList.toggle('active',mode==='signup');
 $('#authTitle').textContent=mode==='login'?'Welcome back':'Create your account'; $('#authSubtitle').textContent=mode==='login'?'Login to your Shurangan account.':'Choose your role and create your academy account.';
}
function handleLogin(e){e.preventDefault();const email=$('#loginEmail').value.trim().toLowerCase(),password=$('#loginPassword').value;const u=users().find(x=>x.email.toLowerCase()===email&&x.password===password);if(!u){showToast('Invalid email or password.');return}login(u)}
function handleSignup(e){e.preventDefault();const u={name:$('#signupName').value.trim(),email:$('#signupEmail').value.trim().toLowerCase(),phone:$('#signupPhone').value.trim(),password:$('#signupPassword').value,role:$('#signupRole').value};if(users().some(x=>x.email.toLowerCase()===u.email)){showToast('An account with this email already exists.');return}const list=users();list.push(u);saveUsers(list);login(u);showToast('Account created successfully.');}
function login(u){localStorage.setItem(CURRENT_KEY,JSON.stringify(u));closeAuth();openDashboard(u)}
function logout(){localStorage.removeItem(CURRENT_KEY);$('#dashboard').classList.add('hidden');document.body.style.overflow='';location.hash='home';showToast('You have been logged out.');}
function roleName(r){return {student:'Student',teacher:'Teacher',admin:'System Admin'}[r]||r}
function openDashboard(u){$('#dashboard').classList.remove('hidden');document.body.style.overflow='hidden';$('#dashRole').textContent=roleName(u.role);$('#dashUser').innerHTML=`<strong>${escapeHtml(u.name)}</strong>${escapeHtml(u.email)}`;renderNav(u.role);renderDashboard(u,'overview')}
function renderNav(role){const items=role==='student'?[['overview','Overview'],['attendance','Attendance'],['exams','Exams & Results'],['payments','Payments'],['profile','Profile']]:role==='teacher'?[['overview','Overview'],['batches','My Batches'],['attendance','Student Attendance'],['classes','Classes & Schedule'],['profile','Profile']]:[['overview','Overview'],['users','User Management'],['programs','Programs & Batches'],['finance','Payments & Reports'],['settings','System Settings']];$('#dashNav').innerHTML=items.map(([id,label])=>`<button data-page="${id}" onclick="renderDashboard(currentUser(),'${id}')">${label}</button>`).join('')}
function currentUser(){return JSON.parse(localStorage.getItem(CURRENT_KEY)||'null')}
function renderDashboard(user,page='overview'){if(!user)return;document.querySelectorAll('#dashNav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const c=$('#dashContent');if(user.role==='student')c.innerHTML=studentPage(user,page);if(user.role==='teacher')c.innerHTML=teacherPage(user,page);if(user.role==='admin')c.innerHTML=adminPage(user,page)}
function shell(u,title,body){return `<div class="dash-welcome"><h1>${title}</h1><p>${roleName(u.role)} account • Shurangan Digital Academy</p></div>${body}`}
function studentPage(u,p){if(p==='attendance')return shell(u,'Attendance',`<div class="dashboard-grid"><div class="dash-stat"><small>Total Classes</small><b>24</b></div><div class="dash-stat"><small>Present</small><b>22</b></div><div class="dash-stat"><small>Absent</small><b>02</b></div><div class="dash-stat"><small>Attendance Rate</small><b>91.7%</b></div></div><div class="dash-panel"><h3>Recent Attendance</h3><table class="dash-table"><tr><th>Date</th><th>Class</th><th>Status</th></tr><tr><td>10 Aug</td><td>Rabindra Sangeet</td><td><span class="status">Present</span></td></tr><tr><td>07 Aug</td><td>Vocal Practice</td><td><span class="status">Present</span></td></tr><tr><td>03 Aug</td><td>Rabindra Sangeet</td><td><span class="status warn">Absent</span></td></tr></table></div>`);if(p==='exams')return shell(u,'Exams & Results',`<div class="dash-panel"><h3>Academic Results</h3><table class="dash-table"><tr><th>Exam</th><th>Subject</th><th>Marks</th><th>Grade</th></tr><tr><td>Midterm Assessment</td><td>Rabindra Sangeet</td><td>87/100</td><td>A+</td></tr><tr><td>Semester Examination</td><td>Voice & Rhythm</td><td>82/100</td><td>A</td></tr></table></div>`);if(p==='payments')return shell(u,'Payments',`<div class="dashboard-grid"><div class="dash-stat"><small>Monthly Fee</small><b>৳1,500</b></div><div class="dash-stat"><small>Due</small><b>৳0</b></div><div class="dash-stat"><small>Last Payment</small><b>৳1,500</b></div><div class="dash-stat"><small>Status</small><b>Paid</b></div></div><div class="dash-panel"><h3>Payment History</h3><table class="dash-table"><tr><th>Date</th><th>Method</th><th>Amount</th><th>Status</th></tr><tr><td>01 Aug</td><td>bKash</td><td>৳1,500</td><td><span class="status">Paid</span></td></tr></table></div>`);if(p==='profile')return shell(u,'My Profile',profile(u));return shell(u,`Welcome, ${escapeHtml(u.name)}!`,`<div class="dashboard-grid"><div class="dash-stat"><small>Current Batch</small><b>Rabindra-12</b></div><div class="dash-stat"><small>Attendance</small><b>91.7%</b></div><div class="dash-stat"><small>Latest Result</small><b>A+</b></div><div class="dash-stat"><small>Fee Status</small><b>Paid</b></div></div><div class="dash-panel"><h3>Today's Schedule</h3><table class="dash-table"><tr><th>Time</th><th>Class</th><th>Room</th><th>Status</th></tr><tr><td>4:00 PM</td><td>Rabindra Sangeet</td><td>Room 102</td><td><span class="status">Scheduled</span></td></tr></table></div>`)}
function teacherPage(u,p){if(p==='batches')return shell(u,'My Batches',`<div class="dash-panel"><h3>Assigned Batches</h3><table class="dash-table"><tr><th>Batch</th><th>Program</th><th>Students</th><th>Schedule</th></tr><tr><td>Rabindra-12</td><td>Rabindra Sangeet</td><td>26</td><td>Sat 4:00 PM</td></tr><tr><td>Music-05</td><td>Vocal Practice</td><td>18</td><td>Tue 5:30 PM</td></tr></table></div>`);if(p==='attendance')return shell(u,'Student Attendance',`<div class="dash-panel"><h3>Rabindra-12 • Today</h3><table class="dash-table"><tr><th>Student ID</th><th>Student</th><th>Status</th></tr><tr><td>ST-1021</td><td>Rafi Hasan</td><td><span class="status">Present</span></td></tr><tr><td>ST-1022</td><td>Tanjima Rahman</td><td><span class="status warn">Absent</span></td></tr></table></div>`);if(p==='classes')return shell(u,'Classes & Schedule',`<div class="dash-panel"><h3>This Week</h3><table class="dash-table"><tr><th>Day</th><th>Time</th><th>Batch</th><th>Room</th></tr><tr><td>Saturday</td><td>4:00 PM</td><td>Rabindra-12</td><td>102</td></tr><tr><td>Tuesday</td><td>5:30 PM</td><td>Music-05</td><td>101</td></tr></table></div>`);if(p==='profile')return shell(u,'My Profile',profile(u));return shell(u,`Welcome, ${escapeHtml(u.name)}!`,`<div class="dashboard-grid"><div class="dash-stat"><small>My Batches</small><b>2</b></div><div class="dash-stat"><small>Students</small><b>44</b></div><div class="dash-stat"><small>Today's Classes</small><b>1</b></div><div class="dash-stat"><small>Avg. Attendance</small><b>94%</b></div></div><div class="dash-panel"><h3>Today's Responsibility</h3><table class="dash-table"><tr><th>Time</th><th>Batch</th><th>Subject</th><th>Task</th></tr><tr><td>4:00 PM</td><td>Rabindra-12</td><td>Rabindra Sangeet</td><td><span class="status">Take Attendance</span></td></tr></table></div>`)}
function adminPage(u,p){if(p==='users')return shell(u,'User Management',`<div class="admin-banner"><b>Academy Users</b><p>Manage student, teacher and administrative accounts.</p></div><div class="dash-panel"><table class="dash-table"><tr><th>Name</th><th>Email</th><th>Role</th></tr>${users().map(x=>`<tr><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.email)}</td><td>${roleName(x.role)}</td></tr>`).join('')}</table></div>`);if(p==='programs')return shell(u,'Programs & Batches',`<div class="dashboard-grid"><div class="dash-stat"><small>Programs</small><b>12</b></div><div class="dash-stat"><small>Active Batches</small><b>18</b></div><div class="dash-stat"><small>Students</small><b>256</b></div><div class="dash-stat"><small>Teachers</small><b>32</b></div></div><div class="dash-panel"><h3>Main Programs</h3><table class="dash-table"><tr><th>Program</th><th>Department</th><th>Batches</th><th>Status</th></tr><tr><td>Rabindra Sangeet Foundation</td><td>Music</td><td>6</td><td><span class="status">Active</span></td></tr><tr><td>Bangladeshi Folk Dance</td><td>Dance</td><td>4</td><td><span class="status">Active</span></td></tr></table></div>`);if(p==='finance')return shell(u,'Payments & Reports',`<div class="dashboard-grid"><div class="dash-stat"><small>Collected This Month</small><b>৳3.8L</b></div><div class="dash-stat"><small>Outstanding</small><b>৳42K</b></div><div class="dash-stat"><small>Transactions</small><b>187</b></div><div class="dash-stat"><small>Success Rate</small><b>98%</b></div></div><div class="dash-panel"><h3>Recent Transactions</h3><table class="dash-table"><tr><th>Date</th><th>Payment ID</th><th>Amount</th><th>Status</th></tr><tr><td>10 Aug</td><td>PAY-2031</td><td>৳1,500</td><td><span class="status">Successful</span></td></tr></table></div>`);if(p==='settings')return shell(u,'System Settings',`<div class="dash-panel"><h3>Academy Configuration</h3><p class="body-copy">Manage departments, programs, batches, classrooms, examinations, attendance, payments and certificates. The Oracle database can be connected to these modules later.</p></div>`);return shell(u,'System Admin',`<div class="admin-banner"><b>Shurangan Academy Control Center</b><p>Central administrative control for the entire academy.</p></div><div class="dashboard-grid"><div class="dash-stat"><small>Students</small><b>256</b></div><div class="dash-stat"><small>Teachers</small><b>32</b></div><div class="dash-stat"><small>Batches</small><b>18</b></div><div class="dash-stat"><small>Today's Attendance</small><b>92%</b></div></div><div class="dash-panel"><h3>Administrative Overview</h3><p class="body-copy">Manage users, programs, batches, payments, examinations, results and reports from one role-based dashboard.</p></div>`)}
function profile(u){return `<div class="dash-panel"><h3>Personal Information</h3><table class="dash-table"><tr><th>Name</th><td>${escapeHtml(u.name)}</td></tr><tr><th>Email</th><td>${escapeHtml(u.email)}</td></tr><tr><th>Phone</th><td>${escapeHtml(u.phone)}</td></tr><tr><th>Role</th><td>${roleName(u.role)}</td></tr></table></div>`}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),3000)}
window.openAuth=openAuth;window.closeAuth=closeAuth;window.switchAuth=switchAuth;window.handleLogin=handleLogin;window.handleSignup=handleSignup;window.logout=logout;window.renderDashboard=renderDashboard;window.currentUser=currentUser;
$('#menuBtn').addEventListener('click',()=>$('#mobileMenu').classList.toggle('hidden'));
$('#dashMenuBtn').addEventListener('click',()=>$('#dashboard .dash-sidebar').classList.toggle('open'));
const sections=[...document.querySelectorAll('main section[id]')],links=[...document.querySelectorAll('.nav-link')];const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)links.forEach(l=>l.classList.toggle('active',l.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-35% 0px -55% 0px'});sections.forEach(s=>observer.observe(s));
const existing=localStorage.getItem(CURRENT_KEY);if(existing){try{openDashboard(JSON.parse(existing))}catch(e){localStorage.removeItem(CURRENT_KEY)}}
